config/routes.rb
Rails.application.routes.draw do
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new 
  end

  def create 
    @person = Person.new(page_params)

    if @person.save
      redirect_to pages_path 
    else
      render :new
    end 
  end 

  private 
    def pages_params
      params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
    end 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1> People </h1>
<p><%= link_to 'New Person', new_person_path %></p>
<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <%= link_to 'Show Page', person_path(person) %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :alive %>
  <%= f.check_box :alive %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<h3><%= @person.age %></h3>
<h3><%= @person.hair_color %></h3>
<h3><%= @person.eye_color %></h3>
<h3><%= @person.gender %></h3>
<h3><%= @person.alive %></h3>
<%= link_to 'Back', people_path %>